<?php

namespace Database\Factories;

use App\Models\University;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * Factory: ReportSnapshotFactory
 *
 * Generates realistic analytical report snapshot records for testing and seeding.
 *
 * Purpose:
 * - Simulates stored analytics snapshots generated by university admins.
 * - Supports multiple report types such as alumni growth, engagement, jobs activity,
 *   mentorship summaries, and event attendance.
 *
 * Behavior:
 * - Automatically creates a University using its factory.
 * - Randomly selects a report type from a predefined list.
 * - Generates snapshot_data as a JSON-encoded structure containing:
 *      - total_alumni
 *      - active_last_30_days
 *      - generated_note
 * - Automatically creates the user who generated the report.
 * - Generates a realistic generated_at timestamp within the last 6 months.
 *
 * Usage:
 * - ReportSnapshot::factory()->create();
 * - ReportSnapshot::factory()->count(10)->create();
 *
 * Related Models:
 * - App\Models\ReportSnapshot
 * - App\Models\University
 * - App\Models\User
 */
class ReportSnapshotFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed> The attributes used to create the model.
     */
    public function definition(): array
    {
        return [
            'university_id' => University::factory(),

            // Type of analytics snapshot
            'report_type' => $this->faker->randomElement([
                'alumni_growth',
                'engagement_overview',
                'jobs_activity',
                'mentorship_summary',
                'event_attendance',
            ]),

            // JSON snapshot data
            'snapshot_data' => json_encode([
                'total_alumni'        => $this->faker->numberBetween(100, 5000),
                'active_last_30_days' => $this->faker->numberBetween(10, 1000),
                'generated_note'      => 'fake data from factory',
            ]),

            // User who generated the report
            'generated_by' => User::factory(),

            // Timestamp of report generation
            'generated_at' => $this->faker->dateTimeBetween('-6 months', 'now'),
        ];
    }
}
